import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="mytheme">
      <body
        className={`${inter.className} bg-secondary text-base-100 min-h-screen`}
      >
        <Navbar />
        <div className="min-h-screen flex pt-[4rem]">
          {" "}
          {/* Adjust the padding-top based on the height of your Navbar */}
          <div className="fixed top-[4rem] left-0 w-[15%] border-r-2 border-slate-500 h-[calc(100vh-4rem)] pt-10">
            <Link href="/" className="ml-10 text-xl text-white btn btn-ghost">
              Dashboard
            </Link>
            <Link
              href="/organizations"
              className="ml-10 text-xl text-white btn btn-ghost"
            >
              Organizations
            </Link>
          </div>
          <div className="w-[85%] min-h-screen pl-[15%]">{children}</div>
        </div>
      </body>
    </html>
  );
}